name: portal
version: 0.1.0
main: com.github.bcTornado608.papermcportal.Portal
description: PORTALLLL AWAY!!!
author: bcTornado608
website: https://github.com/bcTornado608/papermc-portal
api-version: '1.20'

commands:
